version: 2

sources:
  - name: STAGE
    database: MY_DBT_PROJECT
    schema: STAGE
    tables:
      - name: Customer
      - name: LineItem
      - name: Nation
      - name: Orders
      - name: Part
      - name: Partsupp
      - name: Region
      - name: Supplier
